#!/bin/bash

# run.sh environmnet
export VERSION_CHECK=1
echo "VERSION_CHECK : ${VERSION_CHECK}"
export INSTALL_HOST_PKG=0
echo "INSTALL_HOST_PKG : ${INSTALL_HOST_PKG}"
export CHECK_PARTITION=0
echo "CHECK_PARTITION : ${CHECK_PARTITION}"
export DOWNLOAD_LFS_PKG=0
echo "DOWNLOAD_LFS_PKG : ${DOWNLOAD_LFS_PKG}"


# host environment
export CHECK_MOUNT=1
echo "CHECK_MOUNT : ${CHECK_MOUNT}"

export LFS_INIT=1
echo "LFS_INIT : ${LFS_INIT}"
