#!/bin/bash

export VERSION_CHECK=1
echo "VERSION_CHECK : ${VERSION_CHECK}"
export INSTALL_HOST_PKG=0
echo "INSTALL_HOST_PKG : ${INSTALL_HOST_PKG}"
export CHECK_PARTITION=1
echo "CHECK_PARTITION : ${CHECK_PARTITION}"
